version: '3'

services:
  postgres:
    container_name: postgres-uniswap
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uniswap
    ports:
      - 5436:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data